const data = [ { '1. symbol': 'AAPL',
'2. name': 'Apple Inc.',
'3. type': 'Equity',
'4. region': 'United States',
'5. marketOpen': '09:30',
'6. marketClose': '16:00',
'7. timezone': 'UTC-05',
'8. currency': 'USD',
'9. matchScore': '0.8889' },
{ '1. symbol': 'APLE',
'2. name': 'Apple Hospitality REIT Inc.',
'3. type': 'Equity',
'4. region': 'United States',
'5. marketOpen': '09:30',
'6. marketClose': '16:00',
'7. timezone': 'UTC-05',
'8. currency': 'USD',
'9. matchScore': '0.8000' },
{ '1. symbol': 'APRU',
'2. name': 'Apple Rush Company Inc.',
'3. type': 'Equity',
'4. region': 'United States',
'5. marketOpen': '09:30',
'6. marketClose': '16:00',
'7. timezone': 'UTC-05',
'8. currency': 'USD',
'9. matchScore': '0.6667' },
{ '1. symbol': 'APPLX',
'2. name': 'Appleseed Fund Investor Share',
'3. type': 'Mutual Fund',
'4. region': 'United States',
'5. marketOpen': '09:30',
'6. marketClose': '16:00',
'7. timezone': 'UTC-05',
'8. currency': 'USD',
'9. matchScore': '0.6667' },
{ '1. symbol': 'APPIX',
'2. name': 'Appleseed Fund Institutional Share',
'3. type': 'Mutual Fund',
'4. region': 'United States',
'5. marketOpen': '09:30',
'6. marketClose': '16:00',
'7. timezone': 'UTC-05',
'8. currency': 'USD',
'9. matchScore': '0.6667' },
{ '1. symbol': 'GAPJ',
'2. name': 'Golden Apple Oil & Gas Inc.',
'3. type': 'Equity',
'4. region': 'United States',
'5. marketOpen': '09:30',
'6. marketClose': '16:00',
'7. timezone': 'UTC-05',
'8. currency': 'USD',
'9. matchScore': '0.6000' },
{ '1. symbol': 'AAPL.MEX',
'2. name': 'Apple Inc.',
'3. type': 'Equity',
'4. region': 'Mexico',
'5. marketOpen': '08:30',
'6. marketClose': '15:00',
'7. timezone': 'UTC-06',
'8. currency': 'MXP',
'9. matchScore': '0.4444' },
{ '1. symbol': 'AAPL.ARG',
'2. name': 'Apple Inc.',
'3. type': 'Equity',
'4. region': 'Argentina',
'5. marketOpen': '11:00',
'6. marketClose': '17:00',
'7. timezone': 'UTC-03',
'8. currency': 'ARS',
'9. matchScore': '0.4444' } ];

export default data;